ARDUINO_DIR = /opt/arduino-1.0

BOARD_TAG    = uno
#ARDUINO_PORT = /dev/ttyACM0


BOARD_TAG    = pro328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = LiquidCrystal Timer1

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include $(ARDUINO_DIR)/Arduino.mk

