ARDUINO_DIR = /opt/arduino-1.0

BOARD_TAG    = uno
ARDUINO_PORT = /dev/cu.usb*

ARDUINO_LIBS = LiquidCrystal Timer1

AVR_TOOLS_PATH   = /usr/bin
AVRDUDE_CONF     = /etc/avrdude.conf

include $(ARDUINO_DIR)/Arduino.mk

