
# This is done in .bashrc for differences in install dirs
#ARDUINO_DIR = /opt/arduino-1.0

BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

USER_LIB_PATH=/home/ghampton/arduino/Arduino/libraries
ARDUINO_LIBS = Wire Wire/utility PString Adafruit_RGBLCDShield TimerOne


ARDMK_DIR     = /usr/local
AVR_TOOLS_DIR   = /usr
AVRDUDE_CONF     = /etc/avrdude.conf

include ../Arduino.mk

